version: '2'
services:
  previewsapi:
    build:
      context: .
      args:
        - env=development
    command: ['npm', 'run', 'devstart']
    volumes:
      - './acedata/:/data:ro'
      - .:/opt/apps/previews-service
    ports:
      - 8100:8100
