version: '2'
services:
  ace_data:
    image: chooban/ace-data-container
  web:
    build:
      context: .
      args:
        - env=development
    command: ['npm', 'run', 'devstart']
    depends_on:
      - ace_data
    volumes_from:
      - ace_data:ro
    ports:
      - 8100:8100
    volumes:
      - .:/opt/apps/previews-service
