version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: previews-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: previews-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn test
      - setup_remote_docker:
          version: 17.03.0-ce
      - run: |
          TAG=latest
          docker build -t chooban/ace-previews-api:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push chooban/ace-previews-api:$TAG
