version: 2
jobs:
  build:
    docker:
      - image: mhart/alpine-node:8.9.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: previews-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: previews-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn test
